

def limpieza_tipo(df):

    df.Tipo = df.Tipo.str.replace(r'(€+)', '', regex=True)
    df.Tipo = df.Tipo.str.replace('Asiática','')
    df.Tipo = df.Tipo.str.replace(r'.*Ita.*', 'Italiana', regex=True)
    df.Tipo = df.Tipo.str.replace(r'Japonesa, [A-Za-z]+', 'Japonesa', regex=True)
    df.Tipo = df.Tipo.str.replace(r'China, [A-Za-z]+', 'China', regex=True)
    df.Tipo = df.Tipo.str.replace(r'Mexicana, [A-Za-z]+', 'Mexicana', regex=True)
    df.Tipo = df.Tipo.str.replace(r'Americana, [A-Za-z]+', 'Americana', regex=True)
    df.Tipo = df.Tipo.str.replace(r'Shushi [A-Za-z]+', 'Japonesa', regex=True)
    df.Tipo = df.Tipo.str.replace('Italianaánea','Italiana')
    df.Tipo = df.Tipo.str.replace('Americanaña','Americana')
    df.Tipo = df.Tipo.str.replace('Japonesaé','Japonesa')
    df.Tipo = df.Tipo.str.replace('Mexicanaña','Mexicana')
    df.Tipo = df.Tipo.str.replace('Chinaé','China')
    df.Tipo = df.Tipo.str.replace(', ','')
    df.Tipo = df.Tipo.str.replace('InternacionalSushi','Sushi')
    df.Tipo = df.Tipo.str.replace('IndiaInternacional', 'India')
    df.Tipo = df.Tipo.str.replace('CaribeñaLatina','Caribeña')
    df.Tipo = df.Tipo.str.replace('CaribeñaLatina','Caribeña')
    df.Tipo = df.Tipo.str.replace('PeruanaLatina','Peruana')
    df.Tipo = df.Tipo.str.replace('LatinaVenezolana','Venezolana')
    df.Tipo = df.Tipo.str.replace('FrancesaCaribeña','Caribeña')
    df.Tipo = df.Tipo.str.replace('MediterráneaSaludable','Mediterránea')
    df.Tipo = df.Tipo.str.replace('IndiaSaludable','India')
    df.Tipo = df.Tipo.str.replace('LatinaColombiana','Colombiana')
    df.Tipo = df.Tipo.str.replace('TurcaDe Oriente Medio','Turca')
    df.Tipo = df.Tipo.str.replace('Sushi','Japonesa')
    df.Tipo = df.Tipo.str.replace('Restaurante de carneBarbacoa','Argentino')
    